name: 'UUV NPM Publish'

on:
  push:
    tags: [ "*"]

env:
  NODE_VERSION: 18.14.0
  NPM_PACKAGE_SCOPE: uuv

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Download release npm package
        id: "downloadReleasePackage"
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "e2e-test-quest/uuv"
          tag: "${{github.ref_name}}"
          fileName: "*.tgz"
      - name: Publish @uuv/assistant
        uses: ./.github/actions/npm-publish
        with:
          node-version: ${{env.NODE_VERSION}}
          npm-package-scope: ${{env.NPM_PACKAGE_SCOPE}}
          npm-token: ${{secrets.NPM_TOKEN}}
          archive-to-upload: ${{fromJson(steps.downloadReleasePackage.outputs.downloaded_files)[0]}}
